<center><img src="https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80" width="1000" height="600"></center>

<b><h2><center>CRED Case Study</center></h2></b>

DONE BY: K.NIVEDSAGAR


## Problem Definition

### **Business Context**

**CRED** is a consultation firm that partners with banks and checks if their customers are eligible for a credit card. They are a startup just at the roots of starting their business. They have partnered with a few banks and are currently collecting data for credit card applications.


### **Objective**
You have been hired as a Data Scientist to handle and organize the data. You are responsible to organise the data so that, it will be easily accessible and help the company predict, if the application can be accepted for a credit card or not. 

#### **Solution Approach**
You have tried to understand how the credit card works and what all factors come into play. You can organize the data so that the company can help banks to provide credit cards to the customers. You have considered some features related to credit card applications. Some of them are Customer ID, Credit score, age of customer, debt status, and the number of existing credit cards.

Following is the data that you have extracted and listed down, Let's try to build it into data that can be easily accessible and we can gain some insights from it.

| cid | credit_score | age_of_customer | debt_status| no_of_existing_credit_cards|
| --- | --- | --- | --- | --- | 
| cid-0011 | 650 | 25 | in-debt | 3 |
| cid-0012 | 723 | 28 | no debt | 2 |
| cid-0013 | 581 | 38 | no-debt | 4 |
| cid-0014 | 462 | 41 | in-debt | 1 |
| cid-0015 | 773 | 62 | no-debt | 2 |


## 1.0 Organizing data in appropriate format

### 1.1 Storing customer details as variables

Let's start with storing the information in the form of variables and try to work with them.

Let's try to create a variable to store a feature **customerid**

**Question - 1 Create a variable with name cid and a value is stored as cid-0011 in the variable**

In [1]:
cid = "cid-0011"

**Question - 2 Display the value of the variable or a statement one using print and another statement using f-string**

In [2]:
# print statement

print(cid)

# print statement with f string

print(f"Customer ID is {cid}")

cid-0011
Customer ID is cid-0011

Well this works, let's save other customer id's in the same manner.

**What are Variables ?**

>Variables are used to store any type of data.
* A variable name must start with a letter or the underscore character
* A variable name cannot start with a number
* A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _)
* Variable names are case-sensitive (age, Age and AGE are three different variables)

But if we proceed this way we will have to create multiple variables to store a single feature **(this is not an ideal way to store or access data)**


What if we try to store this data as a list ?

### 1.2 Organizing and querying the data

**Question - 3 What is a List?**

A list is a Python data structure used to store multiple values in a single variable.

**Question - 4 How do we define a list?**

A list in Python is defined using square brackets []. Elements inside the list are separated by commas.

**Question - 5 Create customer ID list with 5 elements**

In [3]:
cust_id = ["cid-0011","cid-0012","cid-0013","cid-0014","cid-0015"]

**Question - 6 Print the list to see if this works**

In [4]:
print(cust_id)

['cid-0011', 'cid-0012', 'cid-0013', 'cid-0014', 'cid-0015']

**Question - 7 Create lists for Credit Score, Age of the Customer, Debt Status, and the number of active Credit Cards a customer uses.**

In [5]:
credit_score = [650,723,581,462,773]
age_of_customer = [25,28,38,41,62]
debt_status = ["in-debt","no-debt","no-debt","in-debt","no-debt"]
no_of_existing_credit_cards = [3,2,4,1,2]

**Question - 8 print all the features stored as list**

In [6]:
print(cust_id)
print(credit_score)
print(age_of_customer)
print(debt_status)
print(no_of_existing_credit_cards)

['cid-0011', 'cid-0012', 'cid-0013', 'cid-0014', 'cid-0015']
[650, 723, 581, 462, 773]
[25, 28, 38, 41, 62]
['in-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt']
[3, 2, 4, 1, 2]

Great! now as the lists are created, let's try to fetch some data.

**Question - 9 How are Lists indexed?**

Lists in Python are indexed starting from 0.  
The first element has index 0, the second has index 1, and so on.

**Question - 10 Get data of cid-0012 and print them**

In [7]:
print(cust_id[1])
print(credit_score[1])
print(age_of_customer[1])
print(debt_status[1])
print(no_of_existing_credit_cards[1])

cid-0012
723
28
no-debt
2

Well this is amazing, we can fetch the data in a much organised manner. 

**Question - 11 We just received information that the debt status for cid-0011 needs to be changed as the customer is in debt now. Please update the same in the list.**

In [8]:
#First find the index of cid-0011
index = cust_id.index("cid-0011")

In [9]:
#Then assign the updated status
debt_status[index] = "in-debt"

In [10]:
#print the list debt status
print(debt_status)

['in-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt']

Great! We can see the data updation is easy to do with lists.

### 1.3 Updating customer data based on conditions

We recently got an update from CRED that we need to update the credit score of all users. 
The Credit score is calculated based on 4 factors,

1.   Payment History(High impact)
2.   Credit Utilisation Ratio(High impact)
3.   Age of the Credit(Medium impact)
4.   Total Accounts(Low impact)

Since Payment History has a huge impact on the Credit Score we have to update the score based on the user's history of on-time payment.

For this, first, we have to create a list called **prec_on_time**, which stores the percentage of on-time payments done by the user. If a user's prec_on_time is **greater than 0.7**, then we have to increase their credit score by **2%**. 

Let's also print the customerid for those, whose credit score will be updated. Let's try this out.

In [11]:
# Let's first create the list prec_on_time
# Assume that the below random numbers is the on-time payment percentage
prec_on_time = [0.62, 0.78, 0.20, 0.32, 0.85]

Now, since we want to increase the credit score by 2%, we will first check if the prec_on_time value is greater than 0.7. We can do this with the help of conditional statements.

**What are Conditional Statements?**

> Conditional statements are an important part of decision-making in Python. Results are generated for the satisfied condition.

**If Else Conditional Statement**

> The if-else statement in Python is used for decision-making. The general syntax of an if-else statement is:
```
 if (test expression):
    Body of if
 else:
    Body of else
 ```
>It contains a body of code which runs only when the condition given in the if statement is true. If the condition is false, then the optional else statement runs which contains some code for the else condition.

**Question - 12 Write the code to update the credit_score using if statement**

In [12]:
# if statement code

prec_on_time = [0.62,0.78,0.20,0.32,0.85]

if prec_on_time[1] > 0.7:
    credit_score[1] = credit_score[1] * 1.02

In [13]:
#print the updated credit_score

print(credit_score)

[650, 737.46, 581, 462, 773]

**Question - 13 Enhance the Question-12 code to use the for loop to update the credit_score**

In [14]:
# use the for loop to update the credit score of all the customers by 2% if their on-time payment percentage is greater than 0.75
for i in range(len(credit_score)):
    if prec_on_time[i] > 0.75:
        credit_score[i] = credit_score[i] * 1.02
        print(cust_id[i], "credit score updated")

cid-0012 credit score updated
cid-0015 credit score updated

In [15]:
#print the updated credit_score

print(credit_score)

[650, 752.2092, 581, 462, 788.46]

Great we can see the credit score is updated for cid-0012 and cid-0015. This worked since we had only 5 users but it will be very time consuming and repetitive if we have many users. We should find a better way of coding that allows us to iterate through the list more easily.

Let's say, we have to reduce the credit score for those users whose prec_on_time is less than 40% by 2%

To avoid repetition of code we will use Looping Statements

**What are Looping Statements?**

> Loops are used in Python to iterate over a sequence.

**What are the different types of loops in Python?**

*   For Loop
*   While Loop

**For Loop** 

The syntax of the 'for loop' is:

```
for iterator_var in sequence:
    statements(s)
```
**While Loop**
The syntax of the 'for loop' is:
```
while condition:
    statement(s)
```

We will use for loop in this case

**Question - 14 Using for loop update the credit_score to subtract by 2% if the prec_on_time less than 40%**

In [16]:
for i in range(len(credit_score)):
    if prec_on_time[i] < 0.40:
        credit_score[i] = credit_score[i] * 0.98

print(credit_score)

[650, 752.2092, 569.38, 452.76, 788.46]

Amazing we are now able to run loops and even check conditions with minimal amount of code.

Let's try playing with the data a few more times.

**Question - 15 Find out how many people have credit score greater than 700 and print them ?**

In [17]:
for i in range(len(credit_score)):
    if credit_score[i] > 700:
        print(cust_id[i], credit_score[i])

cid-0012 752.2092
cid-0015 788.46

**Question -16 Check how many people have more than 2 credit cards?**

In [18]:
for i in range(len(no_of_existing_credit_cards)):
    if no_of_existing_credit_cards[i] > 2:
        print(cust_id[i])

cid-0011
cid-0013

**Question - 17 Count how many people are in debt and how many are in not debt ?**

In [19]:
in_debt = 0
not_debt = 0

for status in debt_status:
    if status == "in-debt":
        in_debt += 1
    else:
        not_debt += 1

print("People in debt:", in_debt)
print("People not in debt:", not_debt)

People in debt: 2
People not in debt: 3

**Question - 18 Print all the information of customer whose customer id = cid-0012 - Use For Loop**

In [20]:
for i in range(len(cust_id)):
    if cust_id[i] == "cid-0012":
        print(cust_id[i], credit_score[i], age_of_customer[i], debt_status[i], no_of_existing_credit_cards[i])

cid-0012 752.2092 28 no-debt 2

### 1.4 Modular way of updating data

Awesome! But if we have to check for any other user we will have to write the above code again, that will not be a very ideal way to write code. 

We should try using a function.

**What is a Function in Python?**

>In Python, a function is a block of instructions that performs a specific task.

**Why to use Functions?**
>Functions break the program into modular chunks which can be reused later. Functions are used to make the program more organized and manageable.

**How do we create a Function?**

The syntax for the function is:
```
def function_name(parameters):
	statement(s)
  return statement
```
An optional return statement is used to return value(s) from the function.

**What are parameters in Functions?**
>Parameters are variables through which we pass values to a function. Parameters are optional for function definition.

**Question - 19  Define a function followed by the function name and parameters**

In [21]:
def get_customer_details(cid):
    for i in range(len(cust_id)):
        if cust_id[i] == cid:
            print(cust_id[i], credit_score[i], age_of_customer[i], debt_status[i], no_of_existing_credit_cards[i])

**Question - 20 Call the function to print the details of Customer whose id is 'cid-0011'**

In [22]:
get_customer_details("cid-0011")

cid-0011 650 25 in-debt 3

**Question - 21 Print the details of Customer whose id is 'cid-0012'**

In [23]:
get_customer_details("cid-0012")

cid-0012 752.2092 28 no-debt 2

### 1.5 Combining all the data into a single data element

Amazing! Now we are able to fetch data with a single command.

But as you can see the data is currently segregated into different lists. We are just calling all the lists to fetch the data. In other words, all the lists are independent and we are fetching data by matching the index. We need to club the data into one single structure.

Let's try to combine these into a dictionaries.

**What is a Dictionary?**
>Dictionaries are used to store data values in key:value pairs.

**What's so special about Dictionary?**
>Dictionary items are ordered, changeable, and does not allow duplicates.

**How to declare a Dictionary?**
>Syntax for the dictionary is:
> ```
 dictionary = {'key1':value1,'key2':value2,...,'key_n':value_n}
```

**Question - 22 Create dictionary for all the records with key and value pairs and print the dictionary**

In [24]:
customer_data = {
    "cust_id": cust_id,
    "credit_score": credit_score,
    "age_of_customer": age_of_customer,
    "debt_status": debt_status,
    "no_of_existing_credit_cards": no_of_existing_credit_cards
}

In [25]:
print(customer_data)

{'cust_id': ['cid-0011', 'cid-0012', 'cid-0013', 'cid-0014', 'cid-0015'], 'credit_score': [650, 752.2092, 569.38, 452.76, 788.46], 'age_of_customer': [25, 28, 38, 41, 62], 'debt_status': ['in-debt', 'no-debt', 'no-debt', 'in-debt', 'no-debt'], 'no_of_existing_credit_cards': [3, 2, 4, 1, 2]}

**Question - 23 Fetch all the values under the dictionary key 'cust_id'?**

In [26]:
print(customer_data["cust_id"])

['cid-0011', 'cid-0012', 'cid-0013', 'cid-0014', 'cid-0015']

**Question - 24 fetch the 3rd element in the list 'cust_id'**

In [27]:
print(customer_data["cust_id"][2])

cid-0013

**Question - 25 Get all the information for the Customer whose id is 'cid-0014'**

**HINT: We can do this by iterating the index for a fixed list index. We can achieve that with items() method.**

In [28]:
for i in range(len(customer_data["cust_id"])):
    if customer_data["cust_id"][i] == "cid-0014":
        print(
            customer_data["cust_id"][i],
            customer_data["credit_score"][i],
            customer_data["age_of_customer"][i],
            customer_data["debt_status"][i],
            customer_data["no_of_existing_credit_cards"][i]
        )

cid-0014 452.76 41 in-debt 1

Dictionaries are working well for fetching the existing data, but conditional data pulling will be difficult to achieve in this case. 

If only we had a better way to organize data where it will be organized, systematic, and easy to perform all the operations that we did above.

We can do that by using some libraries which can do all these operations with a single piece of code. Libraries in python contain precompiled codes that can be used for defined operations. They make python programming simpler, as you don't have to create the same functions again and again when you work on a new project. These libraries are readily available and can be called upon by importing the library to the notebook. 

So in this case we will create a dataframe, But for that, we need to import pandas (a library used for data analysis and manipulation)

## 2.0 Getting data into a convenient structure

**What is the Pandas Library?**

Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures. It is fast, flexible, and expressive data structure designed to make working with 'numerical' or 'categorical' data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.

**Why do we use Pandas?**
- Used for analyzing, cleaning, exploring, and manipulating data.

- Pandas allows us to analyze big data and make conclusions.

- It is an important library in data science to get insights from data
<img src="https://www.w3resource.com/w3r_images/pandas-data-structure.svg" />

### 2.1 Converting the dictionary into a pandas dataframe

In [38]:
# import is used to call upon any library that is installed in the system.
import pandas as pd  # anything after 'as' will become an alias for the library name

 **Question - 26 Create a dataframe from the existing dictionary and print the dataframe**

In [39]:
import pandas as pd

df = pd.DataFrame(customer_data)

In [40]:
df

,cust_id,credit_score,age_of_customer,debt_status,no_of_existing_credit_cards
0,cid-0011,650.0000,25,in-debt,3
1,cid-0012,752.2092,28,no-debt,2
2,cid-0013,569.3800,38,no-debt,4
3,cid-0014,452.7600,41,in-debt,1
4,cid-0015,788.4600,62,no-debt,2

Great! this look much better and looks organised, and along with this dataset created we can find a lot's of insights about the data with ease.

### 2.2 Accessing and analysing the data

**Question - 27 Print top 3 data entries from the above created dataframe**

In [41]:
df.head(3)

,cust_id,credit_score,age_of_customer,debt_status,no_of_existing_credit_cards
0,cid-0011,650.0000,25,in-debt,3
1,cid-0012,752.2092,28,no-debt,2
2,cid-0013,569.3800,38,no-debt,4

**Question - 28 Print the last 3 data entries from the above created dataframe**

In [42]:
df.tail(3)

,cust_id,credit_score,age_of_customer,debt_status,no_of_existing_credit_cards
2,cid-0013,569.38,38,no-debt,4
3,cid-0014,452.76,41,in-debt,1
4,cid-0015,788.46,62,no-debt,2

**Question - 29 Create statistical summary of data**

In [43]:
# Let's create statistical summary
df.describe()

       credit_score  age_of_customer  no_of_existing_credit_cards
count      5.000000         5.000000                     5.000000
mean     642.561840        38.800000                     2.400000
std      136.697168        14.584238                     1.140175
min      452.760000        25.000000                     1.000000
25%      569.380000        28.000000                     2.000000
50%      650.000000        38.000000                     2.000000
75%      752.209200        41.000000                     3.000000
max      788.460000        62.000000                     4.000000

**Question - 30 Transpose the dataframe to view the statistical summary in more readable manner**

In [44]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
credit_score,5.0,642.56184,136.697168,452.76,569.38,650.0,752.2092,788.46
age_of_customer,5.0,38.80000,14.584238,25.00,28.00,38.0,41.0000,62.00
no_of_existing_credit_cards,5.0,2.40000,1.140175,1.00,2.00,2.0,3.0000,4.00

**Question - 31 Get the dimension of the data we use shape, that returns a tuple with number of rows and columns**

In [45]:
df.shape

(5, 5)

**Question-32 Get the information about the number of columns, rows datatype and memory usage we use info function**

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   cust_id                      5 non-null      object
 1   credit_score                 5 non-null      float64
 2   age_of_customer              5 non-null      int64
 3   debt_status                  5 non-null      object
 4   no_of_existing_credit_cards  5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes